### ISSUE TITLE
Impossible to translate

### ISSUE THREAD

**Issue by charle-s** [LasLabs/odoo-base#1]
Hi,
I would like translate the warnings messages on the login page.  Ex  "Password must be 12 characters or more. Must contain the following: * Lowercase letter * Uppercase letter * Numeric digit".
Thanks
Charles

**Comment by lasley** [comment]
Hi @charle-s - thanks for the report! We've actually moved this module into OCA & Odoo Apps Support was supposed to delete the other version from their store months ago. I went ahead and pinged them again in the support ticket to hopefully get some movement there.

Take a look at the [password_security](https://www.odoo.com/apps/modules/9.0/password_security/) module instead, which has some more features, is avail on version 8-10, has [translations on the messages](https://github.com/OCA/server-tools/blob/9.0/password_security/models/res_users.py#L46), and even [pre-existing translations](https://github.com/OCA/server-tools/tree/9.0/password_security/i18n)

Sorry about the inconvenience. The ReadMe in this repo has already been updated to reflect the move, but it's in a state of limbo on the apps store right now.

Let us know in [OCA/server-tools](https://github.com/OCA/server-tools) if something still isn't working.

Cheers!
