### ISSUE TITLE
[v10] server_tools password_security issue

### ISSUE THREAD

**Issue by lucode** [LasLabs/odoo-base#3]
I get an annoying issue with the  password_security module. It is not quite clear what triggered the error, perhaps it was due an update of the Odoo core. But suddenly it wasn't possible anymore to login. Either nothing happens or I get a an Error 500. It took a while until I figured out, that the error was caused be that module. Luckily I could migrate the DB to another server and there login was still possible. After uninstalling the website part of that DB I could remigrate the DB to the original server and then login was possible. It did ask then for an new password. That could easily be the real trigger of the error, because it seems that it was not possible to open the dialog to create a new password on the website login page. 
Note: changing of template did not help. 
If this is not a general behaviour, eventually a config file parameter would help to disable the module and get access in any case. Also helpful would be, if not executed password changes or login trials, would be visible in the log file.  Because that module is one which could get easy overlooked when someone tries to figure out what the cause of the blocked login is. 
As it was in my case;)

**Comment by lasley** [comment]
Hi @lucode - thanks for the report. I recommend that you switch to the OCA version of this module, which was released under the name `password_security` vs. the `res_users_password_security` in this repo. This issue was reported on that module in OCA/server-tools#914 and is being fixed in OCA/server-tools#938
